services:
  cinemabackend:
    container_name: "cinemabackend"
    image: "cinema-server"
    build:
     context: .
     dockerfile: cinemaServer/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__dockerDB=Host=cinemaDb;Port=5432;Database=postgres;Username=postgres;Password=postgres;
    networks:
     - data
    ports:
     - "7000:8080"
     - "7001:8081"
    depends_on:
     cinemaDb:
       condition: service_healthy

  cinemaDb:
    image: postgres:16
    container_name: "cinemaDb"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=login_db
    networks: 
      - data
    ports:
      - "5432:5432"
    volumes:
        - './.containers/data:/var/lib/postgresql/data'
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres"]
      interval: 1s
      timeout: 5s
      retries: 5
      start_period: 20s



networks:
  data:
    name: backend_data_connection
    driver: bridge

volumes:
  postgres_data:
    driver: local