services:
  cinemabackend:
    image: postgres:16
    container_name: "cinemabackend"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=login_db
    networks: 
      - data
    ports:
      - "5432:5432"
    volumes:
        - './.containers/data:/var/lib/postgresql/data'
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres"]
      interval: 1s
      timeout: 5s
      retries: 5
      start_period: 20s



networks:
  data:
    name: backend_data_connection
    driver: bridge

volumes:
  postgres_data:
    driver: local