// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using cinemaServer.Data;

#nullable disable

namespace cinemaServer.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("cinemaServer.Models.PureModels.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("movie_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.Property<int>("Runtime")
                        .HasColumnType("integer")
                        .HasColumnName("runtime");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("release_year");

                    b.HasKey("Id");

                    b.ToTable("playable_movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A description",
                            Rating = 1,
                            Runtime = 99,
                            Title = "Some Title",
                            Year = 1987
                        },
                        new
                        {
                            Id = 2,
                            Description = "A description",
                            Rating = 0,
                            Runtime = 69,
                            Title = "Some Title",
                            Year = 2006
                        },
                        new
                        {
                            Id = 3,
                            Description = "A description",
                            Rating = 1,
                            Runtime = 247,
                            Title = "Some Title",
                            Year = 1976
                        },
                        new
                        {
                            Id = 4,
                            Description = "A description",
                            Rating = 2,
                            Runtime = 230,
                            Title = "Some Title",
                            Year = 1978
                        },
                        new
                        {
                            Id = 5,
                            Description = "A description",
                            Rating = 3,
                            Runtime = 278,
                            Title = "Some Title",
                            Year = 2024
                        },
                        new
                        {
                            Id = 6,
                            Description = "A description",
                            Rating = 3,
                            Runtime = 388,
                            Title = "Some Title",
                            Year = 2009
                        },
                        new
                        {
                            Id = 7,
                            Description = "A description",
                            Rating = 0,
                            Runtime = 56,
                            Title = "Some Title",
                            Year = 1970
                        },
                        new
                        {
                            Id = 8,
                            Description = "A description",
                            Rating = 1,
                            Runtime = 46,
                            Title = "Some Title",
                            Year = 2016
                        },
                        new
                        {
                            Id = 9,
                            Description = "A description",
                            Rating = 0,
                            Runtime = 380,
                            Title = "Some Title",
                            Year = 1997
                        },
                        new
                        {
                            Id = 10,
                            Description = "A description",
                            Rating = 4,
                            Runtime = 179,
                            Title = "Some Title",
                            Year = 1957
                        },
                        new
                        {
                            Id = 11,
                            Description = "A description",
                            Rating = 1,
                            Runtime = 368,
                            Title = "Some Title",
                            Year = 2009
                        },
                        new
                        {
                            Id = 12,
                            Description = "A description",
                            Rating = 4,
                            Runtime = 375,
                            Title = "Some Title",
                            Year = 2016
                        },
                        new
                        {
                            Id = 13,
                            Description = "A description",
                            Rating = 1,
                            Runtime = 364,
                            Title = "Some Title",
                            Year = 1979
                        },
                        new
                        {
                            Id = 14,
                            Description = "A description",
                            Rating = 3,
                            Runtime = 237,
                            Title = "Some Title",
                            Year = 1951
                        },
                        new
                        {
                            Id = 15,
                            Description = "A description",
                            Rating = 4,
                            Runtime = 145,
                            Title = "Some Title",
                            Year = 2011
                        },
                        new
                        {
                            Id = 16,
                            Description = "A description",
                            Rating = 4,
                            Runtime = 131,
                            Title = "Some Title",
                            Year = 1975
                        },
                        new
                        {
                            Id = 17,
                            Description = "A description",
                            Rating = 1,
                            Runtime = 369,
                            Title = "Some Title",
                            Year = 2023
                        },
                        new
                        {
                            Id = 18,
                            Description = "A description",
                            Rating = 0,
                            Runtime = 45,
                            Title = "Some Title",
                            Year = 1956
                        },
                        new
                        {
                            Id = 19,
                            Description = "A description",
                            Rating = 3,
                            Runtime = 155,
                            Title = "Some Title",
                            Year = 1961
                        },
                        new
                        {
                            Id = 20,
                            Description = "A description",
                            Rating = 0,
                            Runtime = 53,
                            Title = "Some Title",
                            Year = 1957
                        },
                        new
                        {
                            Id = 21,
                            Description = "A description",
                            Rating = 1,
                            Runtime = 58,
                            Title = "Some Title",
                            Year = 1964
                        },
                        new
                        {
                            Id = 22,
                            Description = "A description",
                            Rating = 2,
                            Runtime = 191,
                            Title = "Some Title",
                            Year = 1994
                        },
                        new
                        {
                            Id = 23,
                            Description = "A description",
                            Rating = 0,
                            Runtime = 146,
                            Title = "Some Title",
                            Year = 2003
                        },
                        new
                        {
                            Id = 24,
                            Description = "A description",
                            Rating = 1,
                            Runtime = 307,
                            Title = "Some Title",
                            Year = 1955
                        },
                        new
                        {
                            Id = 25,
                            Description = "A description",
                            Rating = 1,
                            Runtime = 128,
                            Title = "Some Title",
                            Year = 1985
                        },
                        new
                        {
                            Id = 26,
                            Description = "A description",
                            Rating = 0,
                            Runtime = 212,
                            Title = "Some Title",
                            Year = 2003
                        },
                        new
                        {
                            Id = 27,
                            Description = "A description",
                            Rating = 1,
                            Runtime = 201,
                            Title = "Some Title",
                            Year = 2004
                        },
                        new
                        {
                            Id = 28,
                            Description = "A description",
                            Rating = 0,
                            Runtime = 151,
                            Title = "Some Title",
                            Year = 1983
                        },
                        new
                        {
                            Id = 29,
                            Description = "A description",
                            Rating = 3,
                            Runtime = 234,
                            Title = "Some Title",
                            Year = 2020
                        },
                        new
                        {
                            Id = 30,
                            Description = "A description",
                            Rating = 3,
                            Runtime = 78,
                            Title = "Some Title",
                            Year = 1997
                        },
                        new
                        {
                            Id = 31,
                            Description = "A description",
                            Rating = 1,
                            Runtime = 166,
                            Title = "Some Title",
                            Year = 2017
                        },
                        new
                        {
                            Id = 32,
                            Description = "A description",
                            Rating = 4,
                            Runtime = 139,
                            Title = "Some Title",
                            Year = 1989
                        },
                        new
                        {
                            Id = 33,
                            Description = "A description",
                            Rating = 1,
                            Runtime = 182,
                            Title = "Some Title",
                            Year = 2015
                        },
                        new
                        {
                            Id = 34,
                            Description = "A description",
                            Rating = 3,
                            Runtime = 128,
                            Title = "Some Title",
                            Year = 2021
                        },
                        new
                        {
                            Id = 35,
                            Description = "A description",
                            Rating = 4,
                            Runtime = 292,
                            Title = "Some Title",
                            Year = 1963
                        },
                        new
                        {
                            Id = 36,
                            Description = "A description",
                            Rating = 3,
                            Runtime = 341,
                            Title = "Some Title",
                            Year = 2006
                        },
                        new
                        {
                            Id = 37,
                            Description = "A description",
                            Rating = 2,
                            Runtime = 338,
                            Title = "Some Title",
                            Year = 2012
                        },
                        new
                        {
                            Id = 38,
                            Description = "A description",
                            Rating = 1,
                            Runtime = 235,
                            Title = "Some Title",
                            Year = 1992
                        },
                        new
                        {
                            Id = 39,
                            Description = "A description",
                            Rating = 3,
                            Runtime = 327,
                            Title = "Some Title",
                            Year = 2004
                        },
                        new
                        {
                            Id = 40,
                            Description = "A description",
                            Rating = 3,
                            Runtime = 86,
                            Title = "Some Title",
                            Year = 2015
                        },
                        new
                        {
                            Id = 41,
                            Description = "A description",
                            Rating = 0,
                            Runtime = 345,
                            Title = "Some Title",
                            Year = 1964
                        },
                        new
                        {
                            Id = 42,
                            Description = "A description",
                            Rating = 0,
                            Runtime = 171,
                            Title = "Some Title",
                            Year = 1980
                        },
                        new
                        {
                            Id = 43,
                            Description = "A description",
                            Rating = 4,
                            Runtime = 78,
                            Title = "Some Title",
                            Year = 2022
                        },
                        new
                        {
                            Id = 44,
                            Description = "A description",
                            Rating = 4,
                            Runtime = 190,
                            Title = "Some Title",
                            Year = 1956
                        },
                        new
                        {
                            Id = 45,
                            Description = "A description",
                            Rating = 3,
                            Runtime = 335,
                            Title = "Some Title",
                            Year = 1965
                        },
                        new
                        {
                            Id = 46,
                            Description = "A description",
                            Rating = 1,
                            Runtime = 273,
                            Title = "Some Title",
                            Year = 1994
                        },
                        new
                        {
                            Id = 47,
                            Description = "A description",
                            Rating = 0,
                            Runtime = 124,
                            Title = "Some Title",
                            Year = 2001
                        },
                        new
                        {
                            Id = 48,
                            Description = "A description",
                            Rating = 4,
                            Runtime = 81,
                            Title = "Some Title",
                            Year = 1968
                        },
                        new
                        {
                            Id = 49,
                            Description = "A description",
                            Rating = 1,
                            Runtime = 147,
                            Title = "Some Title",
                            Year = 2010
                        },
                        new
                        {
                            Id = 50,
                            Description = "A description",
                            Rating = 3,
                            Runtime = 363,
                            Title = "Some Title",
                            Year = 1984
                        },
                        new
                        {
                            Id = 51,
                            Description = "A description",
                            Rating = 4,
                            Runtime = 72,
                            Title = "Some Title",
                            Year = 1970
                        },
                        new
                        {
                            Id = 52,
                            Description = "A description",
                            Rating = 3,
                            Runtime = 238,
                            Title = "Some Title",
                            Year = 1977
                        },
                        new
                        {
                            Id = 53,
                            Description = "A description",
                            Rating = 3,
                            Runtime = 234,
                            Title = "Some Title",
                            Year = 1976
                        },
                        new
                        {
                            Id = 54,
                            Description = "A description",
                            Rating = 3,
                            Runtime = 297,
                            Title = "Some Title",
                            Year = 2007
                        },
                        new
                        {
                            Id = 55,
                            Description = "A description",
                            Rating = 3,
                            Runtime = 271,
                            Title = "Some Title",
                            Year = 1982
                        },
                        new
                        {
                            Id = 56,
                            Description = "A description",
                            Rating = 1,
                            Runtime = 250,
                            Title = "Some Title",
                            Year = 2003
                        },
                        new
                        {
                            Id = 57,
                            Description = "A description",
                            Rating = 0,
                            Runtime = 255,
                            Title = "Some Title",
                            Year = 1961
                        },
                        new
                        {
                            Id = 58,
                            Description = "A description",
                            Rating = 0,
                            Runtime = 210,
                            Title = "Some Title",
                            Year = 2016
                        },
                        new
                        {
                            Id = 59,
                            Description = "A description",
                            Rating = 4,
                            Runtime = 212,
                            Title = "Some Title",
                            Year = 2007
                        },
                        new
                        {
                            Id = 60,
                            Description = "A description",
                            Rating = 3,
                            Runtime = 140,
                            Title = "Some Title",
                            Year = 1955
                        },
                        new
                        {
                            Id = 61,
                            Description = "A description",
                            Rating = 2,
                            Runtime = 334,
                            Title = "Some Title",
                            Year = 1963
                        },
                        new
                        {
                            Id = 62,
                            Description = "A description",
                            Rating = 4,
                            Runtime = 101,
                            Title = "Some Title",
                            Year = 1975
                        },
                        new
                        {
                            Id = 63,
                            Description = "A description",
                            Rating = 4,
                            Runtime = 338,
                            Title = "Some Title",
                            Year = 1971
                        },
                        new
                        {
                            Id = 64,
                            Description = "A description",
                            Rating = 1,
                            Runtime = 46,
                            Title = "Some Title",
                            Year = 1958
                        },
                        new
                        {
                            Id = 65,
                            Description = "A description",
                            Rating = 4,
                            Runtime = 218,
                            Title = "Some Title",
                            Year = 1987
                        },
                        new
                        {
                            Id = 66,
                            Description = "A description",
                            Rating = 4,
                            Runtime = 178,
                            Title = "Some Title",
                            Year = 1983
                        },
                        new
                        {
                            Id = 67,
                            Description = "A description",
                            Rating = 0,
                            Runtime = 64,
                            Title = "Some Title",
                            Year = 2002
                        },
                        new
                        {
                            Id = 68,
                            Description = "A description",
                            Rating = 1,
                            Runtime = 381,
                            Title = "Some Title",
                            Year = 1973
                        },
                        new
                        {
                            Id = 69,
                            Description = "A description",
                            Rating = 1,
                            Runtime = 270,
                            Title = "Some Title",
                            Year = 1995
                        },
                        new
                        {
                            Id = 70,
                            Description = "A description",
                            Rating = 3,
                            Runtime = 324,
                            Title = "Some Title",
                            Year = 1955
                        },
                        new
                        {
                            Id = 71,
                            Description = "A description",
                            Rating = 1,
                            Runtime = 324,
                            Title = "Some Title",
                            Year = 1970
                        },
                        new
                        {
                            Id = 72,
                            Description = "A description",
                            Rating = 2,
                            Runtime = 99,
                            Title = "Some Title",
                            Year = 2016
                        },
                        new
                        {
                            Id = 73,
                            Description = "A description",
                            Rating = 0,
                            Runtime = 140,
                            Title = "Some Title",
                            Year = 1986
                        },
                        new
                        {
                            Id = 74,
                            Description = "A description",
                            Rating = 2,
                            Runtime = 368,
                            Title = "Some Title",
                            Year = 2005
                        },
                        new
                        {
                            Id = 75,
                            Description = "A description",
                            Rating = 0,
                            Runtime = 222,
                            Title = "Some Title",
                            Year = 1995
                        },
                        new
                        {
                            Id = 76,
                            Description = "A description",
                            Rating = 1,
                            Runtime = 353,
                            Title = "Some Title",
                            Year = 2023
                        },
                        new
                        {
                            Id = 77,
                            Description = "A description",
                            Rating = 1,
                            Runtime = 132,
                            Title = "Some Title",
                            Year = 1957
                        },
                        new
                        {
                            Id = 78,
                            Description = "A description",
                            Rating = 1,
                            Runtime = 90,
                            Title = "Some Title",
                            Year = 1966
                        },
                        new
                        {
                            Id = 79,
                            Description = "A description",
                            Rating = 4,
                            Runtime = 224,
                            Title = "Some Title",
                            Year = 2014
                        },
                        new
                        {
                            Id = 80,
                            Description = "A description",
                            Rating = 3,
                            Runtime = 120,
                            Title = "Some Title",
                            Year = 1988
                        },
                        new
                        {
                            Id = 81,
                            Description = "A description",
                            Rating = 1,
                            Runtime = 190,
                            Title = "Some Title",
                            Year = 1952
                        },
                        new
                        {
                            Id = 82,
                            Description = "A description",
                            Rating = 4,
                            Runtime = 127,
                            Title = "Some Title",
                            Year = 1964
                        },
                        new
                        {
                            Id = 83,
                            Description = "A description",
                            Rating = 3,
                            Runtime = 376,
                            Title = "Some Title",
                            Year = 1975
                        },
                        new
                        {
                            Id = 84,
                            Description = "A description",
                            Rating = 4,
                            Runtime = 162,
                            Title = "Some Title",
                            Year = 1958
                        },
                        new
                        {
                            Id = 85,
                            Description = "A description",
                            Rating = 4,
                            Runtime = 297,
                            Title = "Some Title",
                            Year = 1958
                        },
                        new
                        {
                            Id = 86,
                            Description = "A description",
                            Rating = 3,
                            Runtime = 272,
                            Title = "Some Title",
                            Year = 1984
                        },
                        new
                        {
                            Id = 87,
                            Description = "A description",
                            Rating = 3,
                            Runtime = 132,
                            Title = "Some Title",
                            Year = 2006
                        },
                        new
                        {
                            Id = 88,
                            Description = "A description",
                            Rating = 4,
                            Runtime = 387,
                            Title = "Some Title",
                            Year = 1991
                        },
                        new
                        {
                            Id = 89,
                            Description = "A description",
                            Rating = 0,
                            Runtime = 143,
                            Title = "Some Title",
                            Year = 2000
                        },
                        new
                        {
                            Id = 90,
                            Description = "A description",
                            Rating = 0,
                            Runtime = 360,
                            Title = "Some Title",
                            Year = 1997
                        },
                        new
                        {
                            Id = 91,
                            Description = "A description",
                            Rating = 4,
                            Runtime = 294,
                            Title = "Some Title",
                            Year = 1954
                        },
                        new
                        {
                            Id = 92,
                            Description = "A description",
                            Rating = 3,
                            Runtime = 163,
                            Title = "Some Title",
                            Year = 1988
                        },
                        new
                        {
                            Id = 93,
                            Description = "A description",
                            Rating = 2,
                            Runtime = 121,
                            Title = "Some Title",
                            Year = 1970
                        },
                        new
                        {
                            Id = 94,
                            Description = "A description",
                            Rating = 3,
                            Runtime = 115,
                            Title = "Some Title",
                            Year = 2020
                        },
                        new
                        {
                            Id = 95,
                            Description = "A description",
                            Rating = 4,
                            Runtime = 317,
                            Title = "Some Title",
                            Year = 2018
                        },
                        new
                        {
                            Id = 96,
                            Description = "A description",
                            Rating = 0,
                            Runtime = 169,
                            Title = "Some Title",
                            Year = 1980
                        },
                        new
                        {
                            Id = 97,
                            Description = "A description",
                            Rating = 2,
                            Runtime = 187,
                            Title = "Some Title",
                            Year = 2014
                        },
                        new
                        {
                            Id = 98,
                            Description = "A description",
                            Rating = 3,
                            Runtime = 99,
                            Title = "Some Title",
                            Year = 2022
                        },
                        new
                        {
                            Id = 99,
                            Description = "A description",
                            Rating = 2,
                            Runtime = 85,
                            Title = "Some Title",
                            Year = 1982
                        });
                });

            modelBuilder.Entity("cinemaServer.Models.PureModels.People.Customer", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("customer_id");

                    b.Property<int>("Age")
                        .HasColumnType("integer")
                        .HasColumnName("age");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("country");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("cinemaServer.Models.PureModels.Screening", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("screening_id");

                    b.Property<int>("MovieId")
                        .HasColumnType("integer")
                        .HasColumnName("movie_id");

                    b.Property<int>("TheaterId")
                        .HasColumnType("integer")
                        .HasColumnName("theater_id");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id", "MovieId", "TheaterId");

                    b.HasIndex("MovieId");

                    b.HasIndex("TheaterId");

                    b.ToTable("movie_screenings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MovieId = 21,
                            TheaterId = 13,
                            StartTime = new DateTime(2025, 12, 4, 13, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            MovieId = 95,
                            TheaterId = 10,
                            StartTime = new DateTime(2020, 8, 15, 16, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            MovieId = 10,
                            TheaterId = 5,
                            StartTime = new DateTime(2005, 2, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            MovieId = 98,
                            TheaterId = 7,
                            StartTime = new DateTime(2023, 6, 3, 21, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            MovieId = 92,
                            TheaterId = 5,
                            StartTime = new DateTime(2007, 12, 8, 14, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            MovieId = 2,
                            TheaterId = 10,
                            StartTime = new DateTime(2004, 6, 2, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7,
                            MovieId = 86,
                            TheaterId = 18,
                            StartTime = new DateTime(2024, 2, 15, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8,
                            MovieId = 83,
                            TheaterId = 5,
                            StartTime = new DateTime(2000, 3, 29, 20, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 9,
                            MovieId = 54,
                            TheaterId = 18,
                            StartTime = new DateTime(2024, 1, 19, 23, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 10,
                            MovieId = 74,
                            TheaterId = 4,
                            StartTime = new DateTime(2013, 1, 9, 15, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 11,
                            MovieId = 85,
                            TheaterId = 8,
                            StartTime = new DateTime(2016, 12, 7, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 12,
                            MovieId = 99,
                            TheaterId = 7,
                            StartTime = new DateTime(2001, 7, 17, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 13,
                            MovieId = 45,
                            TheaterId = 7,
                            StartTime = new DateTime(2009, 5, 27, 18, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 14,
                            MovieId = 18,
                            TheaterId = 6,
                            StartTime = new DateTime(2002, 11, 11, 14, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 15,
                            MovieId = 74,
                            TheaterId = 6,
                            StartTime = new DateTime(2016, 8, 2, 13, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 16,
                            MovieId = 98,
                            TheaterId = 5,
                            StartTime = new DateTime(2006, 12, 23, 18, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 17,
                            MovieId = 85,
                            TheaterId = 19,
                            StartTime = new DateTime(2003, 12, 20, 14, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 18,
                            MovieId = 46,
                            TheaterId = 6,
                            StartTime = new DateTime(2025, 1, 19, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 19,
                            MovieId = 49,
                            TheaterId = 4,
                            StartTime = new DateTime(2012, 12, 24, 14, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 20,
                            MovieId = 20,
                            TheaterId = 12,
                            StartTime = new DateTime(2014, 5, 7, 19, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 21,
                            MovieId = 45,
                            TheaterId = 2,
                            StartTime = new DateTime(2017, 8, 21, 18, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 22,
                            MovieId = 56,
                            TheaterId = 15,
                            StartTime = new DateTime(2001, 8, 4, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 23,
                            MovieId = 73,
                            TheaterId = 2,
                            StartTime = new DateTime(2001, 11, 26, 15, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 24,
                            MovieId = 47,
                            TheaterId = 4,
                            StartTime = new DateTime(2010, 1, 13, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 25,
                            MovieId = 88,
                            TheaterId = 6,
                            StartTime = new DateTime(2001, 8, 19, 21, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 26,
                            MovieId = 54,
                            TheaterId = 16,
                            StartTime = new DateTime(2017, 3, 17, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 27,
                            MovieId = 41,
                            TheaterId = 14,
                            StartTime = new DateTime(2023, 3, 12, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 28,
                            MovieId = 79,
                            TheaterId = 7,
                            StartTime = new DateTime(2013, 4, 4, 20, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 29,
                            MovieId = 71,
                            TheaterId = 5,
                            StartTime = new DateTime(2010, 12, 19, 16, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 30,
                            MovieId = 39,
                            TheaterId = 3,
                            StartTime = new DateTime(2015, 7, 28, 21, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 31,
                            MovieId = 1,
                            TheaterId = 4,
                            StartTime = new DateTime(2013, 2, 9, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 32,
                            MovieId = 14,
                            TheaterId = 1,
                            StartTime = new DateTime(2000, 9, 26, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 33,
                            MovieId = 74,
                            TheaterId = 2,
                            StartTime = new DateTime(2021, 6, 12, 18, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 34,
                            MovieId = 3,
                            TheaterId = 4,
                            StartTime = new DateTime(2022, 9, 17, 17, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 35,
                            MovieId = 15,
                            TheaterId = 14,
                            StartTime = new DateTime(2003, 3, 23, 16, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 36,
                            MovieId = 64,
                            TheaterId = 18,
                            StartTime = new DateTime(2002, 2, 18, 16, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 37,
                            MovieId = 42,
                            TheaterId = 5,
                            StartTime = new DateTime(2002, 4, 19, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 38,
                            MovieId = 21,
                            TheaterId = 4,
                            StartTime = new DateTime(2020, 4, 19, 8, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 39,
                            MovieId = 77,
                            TheaterId = 6,
                            StartTime = new DateTime(2019, 1, 31, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 40,
                            MovieId = 62,
                            TheaterId = 8,
                            StartTime = new DateTime(2024, 4, 13, 15, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 41,
                            MovieId = 18,
                            TheaterId = 5,
                            StartTime = new DateTime(2022, 12, 12, 20, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 42,
                            MovieId = 30,
                            TheaterId = 2,
                            StartTime = new DateTime(2007, 7, 30, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 43,
                            MovieId = 23,
                            TheaterId = 18,
                            StartTime = new DateTime(2023, 3, 24, 20, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 44,
                            MovieId = 51,
                            TheaterId = 19,
                            StartTime = new DateTime(2013, 4, 20, 15, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 45,
                            MovieId = 83,
                            TheaterId = 8,
                            StartTime = new DateTime(2015, 8, 27, 20, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 46,
                            MovieId = 84,
                            TheaterId = 18,
                            StartTime = new DateTime(2001, 2, 26, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 47,
                            MovieId = 23,
                            TheaterId = 19,
                            StartTime = new DateTime(2020, 8, 28, 13, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 48,
                            MovieId = 17,
                            TheaterId = 7,
                            StartTime = new DateTime(2003, 7, 13, 20, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 49,
                            MovieId = 15,
                            TheaterId = 17,
                            StartTime = new DateTime(2005, 1, 19, 21, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 50,
                            MovieId = 84,
                            TheaterId = 8,
                            StartTime = new DateTime(2013, 4, 30, 16, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 51,
                            MovieId = 64,
                            TheaterId = 17,
                            StartTime = new DateTime(2017, 10, 25, 17, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 52,
                            MovieId = 76,
                            TheaterId = 13,
                            StartTime = new DateTime(2005, 2, 6, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 53,
                            MovieId = 37,
                            TheaterId = 1,
                            StartTime = new DateTime(2003, 9, 4, 8, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 54,
                            MovieId = 28,
                            TheaterId = 3,
                            StartTime = new DateTime(2006, 11, 21, 17, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 55,
                            MovieId = 15,
                            TheaterId = 16,
                            StartTime = new DateTime(2000, 6, 16, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 56,
                            MovieId = 94,
                            TheaterId = 4,
                            StartTime = new DateTime(2013, 10, 28, 23, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 57,
                            MovieId = 43,
                            TheaterId = 8,
                            StartTime = new DateTime(2018, 8, 6, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 58,
                            MovieId = 35,
                            TheaterId = 6,
                            StartTime = new DateTime(2025, 1, 9, 17, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 59,
                            MovieId = 51,
                            TheaterId = 3,
                            StartTime = new DateTime(2001, 8, 9, 15, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 60,
                            MovieId = 13,
                            TheaterId = 15,
                            StartTime = new DateTime(2014, 1, 10, 17, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 61,
                            MovieId = 72,
                            TheaterId = 4,
                            StartTime = new DateTime(2016, 9, 28, 14, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 62,
                            MovieId = 80,
                            TheaterId = 17,
                            StartTime = new DateTime(2005, 6, 29, 18, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 63,
                            MovieId = 56,
                            TheaterId = 3,
                            StartTime = new DateTime(2010, 2, 6, 16, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 64,
                            MovieId = 96,
                            TheaterId = 6,
                            StartTime = new DateTime(2014, 5, 30, 18, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 65,
                            MovieId = 97,
                            TheaterId = 3,
                            StartTime = new DateTime(2005, 4, 25, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 66,
                            MovieId = 1,
                            TheaterId = 15,
                            StartTime = new DateTime(2010, 12, 27, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 67,
                            MovieId = 19,
                            TheaterId = 13,
                            StartTime = new DateTime(2013, 4, 9, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 68,
                            MovieId = 25,
                            TheaterId = 15,
                            StartTime = new DateTime(2025, 3, 8, 15, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 69,
                            MovieId = 48,
                            TheaterId = 2,
                            StartTime = new DateTime(2012, 4, 30, 8, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 70,
                            MovieId = 37,
                            TheaterId = 15,
                            StartTime = new DateTime(2024, 2, 8, 16, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 71,
                            MovieId = 81,
                            TheaterId = 5,
                            StartTime = new DateTime(2003, 5, 10, 16, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 72,
                            MovieId = 57,
                            TheaterId = 19,
                            StartTime = new DateTime(2008, 8, 30, 14, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 73,
                            MovieId = 2,
                            TheaterId = 9,
                            StartTime = new DateTime(2005, 4, 16, 15, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 74,
                            MovieId = 89,
                            TheaterId = 13,
                            StartTime = new DateTime(2003, 10, 27, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 75,
                            MovieId = 22,
                            TheaterId = 7,
                            StartTime = new DateTime(2009, 12, 12, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 76,
                            MovieId = 87,
                            TheaterId = 13,
                            StartTime = new DateTime(2022, 4, 17, 18, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 77,
                            MovieId = 25,
                            TheaterId = 16,
                            StartTime = new DateTime(2007, 6, 26, 13, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 78,
                            MovieId = 97,
                            TheaterId = 11,
                            StartTime = new DateTime(2003, 9, 11, 18, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 79,
                            MovieId = 28,
                            TheaterId = 8,
                            StartTime = new DateTime(2007, 10, 8, 14, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 80,
                            MovieId = 2,
                            TheaterId = 17,
                            StartTime = new DateTime(2005, 10, 30, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 81,
                            MovieId = 74,
                            TheaterId = 12,
                            StartTime = new DateTime(2003, 11, 8, 13, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 82,
                            MovieId = 48,
                            TheaterId = 17,
                            StartTime = new DateTime(2004, 3, 1, 19, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 83,
                            MovieId = 92,
                            TheaterId = 2,
                            StartTime = new DateTime(2001, 12, 16, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 84,
                            MovieId = 18,
                            TheaterId = 4,
                            StartTime = new DateTime(2018, 11, 26, 16, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 85,
                            MovieId = 36,
                            TheaterId = 10,
                            StartTime = new DateTime(2011, 2, 12, 23, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 86,
                            MovieId = 80,
                            TheaterId = 1,
                            StartTime = new DateTime(2015, 7, 2, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 87,
                            MovieId = 98,
                            TheaterId = 9,
                            StartTime = new DateTime(2001, 3, 2, 23, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 88,
                            MovieId = 63,
                            TheaterId = 14,
                            StartTime = new DateTime(2011, 3, 14, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 89,
                            MovieId = 13,
                            TheaterId = 7,
                            StartTime = new DateTime(2025, 12, 31, 20, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 90,
                            MovieId = 19,
                            TheaterId = 8,
                            StartTime = new DateTime(2009, 8, 10, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 91,
                            MovieId = 83,
                            TheaterId = 4,
                            StartTime = new DateTime(2007, 4, 21, 19, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 92,
                            MovieId = 26,
                            TheaterId = 4,
                            StartTime = new DateTime(2000, 11, 18, 16, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 93,
                            MovieId = 45,
                            TheaterId = 5,
                            StartTime = new DateTime(2017, 12, 27, 19, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 94,
                            MovieId = 48,
                            TheaterId = 1,
                            StartTime = new DateTime(2022, 12, 26, 17, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 95,
                            MovieId = 46,
                            TheaterId = 14,
                            StartTime = new DateTime(2013, 12, 29, 14, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 96,
                            MovieId = 1,
                            TheaterId = 10,
                            StartTime = new DateTime(2011, 5, 3, 19, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 97,
                            MovieId = 44,
                            TheaterId = 13,
                            StartTime = new DateTime(2025, 3, 25, 14, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 98,
                            MovieId = 82,
                            TheaterId = 3,
                            StartTime = new DateTime(2019, 5, 25, 18, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 99,
                            MovieId = 44,
                            TheaterId = 14,
                            StartTime = new DateTime(2014, 9, 19, 14, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("cinemaServer.Models.PureModels.Theater", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("theater_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("theater_rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 41,
                            Name = "A theater name"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 143,
                            Name = "A theater name"
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 81,
                            Name = "A theater name"
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 119,
                            Name = "A theater name"
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 14,
                            Name = "A theater name"
                        },
                        new
                        {
                            Id = 6,
                            Capacity = 108,
                            Name = "A theater name"
                        },
                        new
                        {
                            Id = 7,
                            Capacity = 89,
                            Name = "A theater name"
                        },
                        new
                        {
                            Id = 8,
                            Capacity = 95,
                            Name = "A theater name"
                        },
                        new
                        {
                            Id = 9,
                            Capacity = 15,
                            Name = "A theater name"
                        },
                        new
                        {
                            Id = 10,
                            Capacity = 146,
                            Name = "A theater name"
                        },
                        new
                        {
                            Id = 11,
                            Capacity = 63,
                            Name = "A theater name"
                        },
                        new
                        {
                            Id = 12,
                            Capacity = 93,
                            Name = "A theater name"
                        },
                        new
                        {
                            Id = 13,
                            Capacity = 43,
                            Name = "A theater name"
                        },
                        new
                        {
                            Id = 14,
                            Capacity = 70,
                            Name = "A theater name"
                        },
                        new
                        {
                            Id = 15,
                            Capacity = 33,
                            Name = "A theater name"
                        },
                        new
                        {
                            Id = 16,
                            Capacity = 49,
                            Name = "A theater name"
                        },
                        new
                        {
                            Id = 17,
                            Capacity = 14,
                            Name = "A theater name"
                        },
                        new
                        {
                            Id = 18,
                            Capacity = 125,
                            Name = "A theater name"
                        },
                        new
                        {
                            Id = 19,
                            Capacity = 149,
                            Name = "A theater name"
                        });
                });

            modelBuilder.Entity("cinemaServer.Models.PureModels.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ticket_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Column")
                        .HasColumnType("integer")
                        .HasColumnName("column");

                    b.Property<string>("CustomerId")
                        .HasColumnType("text")
                        .HasColumnName("customer_id");

                    b.Property<int>("Row")
                        .HasColumnType("integer")
                        .HasColumnName("row");

                    b.Property<int>("ScreeningId")
                        .HasColumnType("integer")
                        .HasColumnName("screening_id");

                    b.Property<int>("ScreeningMovieId")
                        .HasColumnType("integer");

                    b.Property<int>("ScreeningTheaterId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ScreeningId", "ScreeningMovieId", "ScreeningTheaterId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("cinemaServer.Models.PureModels.Screening", b =>
                {
                    b.HasOne("cinemaServer.Models.PureModels.Movie", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("cinemaServer.Models.PureModels.Theater", "Theater")
                        .WithMany()
                        .HasForeignKey("TheaterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("Theater");
                });

            modelBuilder.Entity("cinemaServer.Models.PureModels.Ticket", b =>
                {
                    b.HasOne("cinemaServer.Models.PureModels.People.Customer", null)
                        .WithMany("Tickets")
                        .HasForeignKey("CustomerId");

                    b.HasOne("cinemaServer.Models.PureModels.Screening", null)
                        .WithMany("Tickets")
                        .HasForeignKey("ScreeningId", "ScreeningMovieId", "ScreeningTheaterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("cinemaServer.Models.PureModels.People.Customer", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("cinemaServer.Models.PureModels.Screening", b =>
                {
                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
